[[constraint]]
  branch = "ripfield"
  name = "github.com/redsift/bleve"

[[constraint]]
  branch = "patched"
  name = "github.com/redsift/blevex"

[[override]]
  branch = "patched"
  name = "github.com/redsift/gorocksdb"
